// Google OAuth Configuration
import passport from 'passport';
import { Strategy as GoogleStrategy } from 'passport-google-oauth20';
import jwt from 'jsonwebtoken';

// Helper function to generate JWT token
export function generateToken(user) {
  const JWT_SECRET = process.env.JWT_SECRET;
  if (!JWT_SECRET) {
    throw new Error('JWT_SECRET not configured');
  }

  return jwt.sign(
    {
      id: user.id,
      username: user.username,
      email: user.email,
      role: user.role
    },
    JWT_SECRET,
    { expiresIn: '7d' } // 7 days expiry
  );
}

// Initialize Google OAuth Strategy
export function initializePassport() {
  const JWT_SECRET = process.env.JWT_SECRET;
  const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
  const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
  const GOOGLE_CALLBACK_URL = process.env.GOOGLE_CALLBACK_URL || 'http://localhost:3001/api/auth/google/callback';

  // Validate configuration
  if (!JWT_SECRET) {
    console.error('❌ FATAL: JWT_SECRET environment variable not set');
    process.exit(1);
  }

  if (!GOOGLE_CLIENT_ID || !GOOGLE_CLIENT_SECRET) {
    console.error('❌ FATAL: Google OAuth credentials not configured');
    console.error('   Please set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in .env file');
    process.exit(1);
  }

  // Configure Google OAuth Strategy
  passport.use(new GoogleStrategy({
    clientID: GOOGLE_CLIENT_ID,
    clientSecret: GOOGLE_CLIENT_SECRET,
    callbackURL: GOOGLE_CALLBACK_URL,
    scope: ['profile', 'email']
  },
    async (accessToken, refreshToken, profile, done) => {
      try {
        const pool = global.pool; // Use global pool from index.js

        const googleId = profile.id;
        const email = profile.emails[0].value;
        const fullName = profile.displayName;
        const avatarUrl = profile.photos[0]?.value;

        // Find or create user
        let user = await pool.query(
          'SELECT * FROM users WHERE google_id = $1',
          [googleId]
        );

        if (user.rows.length === 0) {
          // Check if this is the first user (becomes admin automatically)
          const userCount = await pool.query('SELECT COUNT(*) FROM users');
          const isFirstUser = parseInt(userCount.rows[0].count) === 0;

          // First user = auto-approved admin, others = pending with no role
          const role = isFirstUser ? 'admin' : null;
          const isApproved = isFirstUser;

          // Create new user (employee_id auto-generated by database trigger)
          const username = email.split('@')[0];

          const result = await pool.query(
            `INSERT INTO users (
            google_id, google_email, email, username, full_name, 
            avatar_url, role, is_active, is_approved
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, true, $8) 
          RETURNING *`,
            [googleId, email, email, username, fullName, avatarUrl, role, isApproved]
          );

          user = result;

          console.log(`✅ New user created: ${email} (${result.rows[0].employee_id}) - ${isFirstUser ? 'Admin' : 'Pending approval'}`);

          // Log activity
          await pool.query(
            'INSERT INTO activity_log (user_id, action_type, action_details) VALUES ($1, $2, $3)',
            [user.rows[0].id, 'signup', `User ${fullName} signed up via Google OAuth`]
          );
        } else {
          // Update existing user's login time and avatar
          await pool.query(
            `UPDATE users 
           SET last_login = CURRENT_TIMESTAMP, avatar_url = $1 
           WHERE id = $2`,
            [avatarUrl, user.rows[0].id]
          );

          console.log(`✅ User logged in: ${email}`);
        }

        // Log login activity
        await pool.query(
          'INSERT INTO activity_log (user_id, action_type, action_details) VALUES ($1, $2, $3)',
          [user.rows[0].id, 'login', `User ${fullName} logged in via Google OAuth`]
        );

        return done(null, user.rows[0]);
      } catch (error) {
        console.error('❌ OAuth error:', error);
        return done(error, null);
      }
    }));

  // Serialize user for session
  passport.serializeUser((user, done) => {
    done(null, user.id);
  });

  // Deserialize user from session
  passport.deserializeUser(async (id, done) => {
    try {
      const pool = global.pool;
      const result = await pool.query('SELECT * FROM users WHERE id = $1', [id]);
      done(null, result.rows[0]);
    } catch (error) {
      done(error, null);
    }
  });

  console.log('✅ Google OAuth configured successfully');
}

export default passport;
